SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER ON;
SET NUMERIC_ROUNDABORT OFF;
GO

USE QuanLyDonDatHangDB;
GO

IF COL_LENGTH('dbo.tbl_DonDatHang', 'DaTruKho') IS NULL
BEGIN
    ALTER TABLE dbo.tbl_DonDatHang
        ADD DaTruKho BIT NOT NULL
            CONSTRAINT DF_DonDatHang_DaTruKho DEFAULT 0;
END
GO
